namespace: production

replicaCount: 2

image:
  tag: "1.27.3" # immutable Tag (kein :latest / :stable)

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
